name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: ./gradlew build
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          rerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
