name: release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup jdk17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - run: ./gradlew build

      - name: generate versions
        uses: HardNorth/github-version-generate@v1.1.1
        with:
          version-source: file
          version-file: gradle.properties
          version-file-extraction-pattern: 'version=([\d]+.[\d]+.[\d]+)'
          
      - name: setup git credentials
        run: |
          git config user.name 'Nozemi'
          git config user.email ${{ secrets.EMAIL }}
          git config user.password ${{ secrets.GITHUB_TOKEN }}

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/libs/advent-of-code*.jar
