name: release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup jdk17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - run: ./gradlew build

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/libs/advent-of-code*.jar
