name: version bumper

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup jdk17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: generate versions
        uses: HardNorth/github-version-generate@v1.1.1
        with:
          version-source: file
          version-file: gradle.properties
          version-file-extraction-pattern: 'version=([\d]+.[\d]+.[\d]+)'

      - name: setup git credentials
        run: |
          git config user.name 'Nozemi'
          git config user.email ${{ secrets.EMAIL }}
          git config user.password ${{ secrets.GITHUB_TOKEN }}

      - name: release with gradle
        id: release
        run: |
          ./gradlew release -Prelease.useAutomaticVersion=true \
          -Prelease.releaseVersion=${{ env.RELEASE_VERSION }} \
          -Prelease.newVersion=${{ env.NEXT_VERSION }} \
          -x createReleaseTag